openapi: 3.0.3
info:
  title: Demo TODO application
  description: |-
    This is a sample API which is for testing the code generation out of Maven for usage in Jakarta REST application.
  version: 1.0.0
externalDocs:
  description: Check out the repository
  url: https://github.com/erdlet
tags:
  - name: todos
    description: Every information about todos
paths:
  /todos:
    get:
      description: Returns all todos
      tags:
        - todos
      summary: Get all ToDos
      operationId: index
      responses:
        "200":
          description: Request processed successfully
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
        default:
          description: Any other response, e. g. errors
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Todo:
      required:
        - title
        - description
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: Buy ice cream
        description:
          type: string
          example: What has to be done in detail?
    Error:
      required:
        - status
        - message
      type: object
      properties:
        errorNumber:
          type: integer
          example: ERR-123
        message:
          type: string
          example: "Database error during load process"
  requestBodies:
    Todo:
      description: ToDo content
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Todo'
